# Generated by Django 4.1.7 on 2023-03-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_employee_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catname", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=200)),
                ("cnumber", models.CharField(max_length=10)),
                (
                    "ccategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.categories"
                    ),
                ),
            ],
        ),
    ]
