# Generated by Django 4.1.7 on 2023-04-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_events_eimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="eimage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
