# Generated by Django 4.1.7 on 2023-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_events_eimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="eimage",
            field=models.ImageField(blank=True, null=True, upload_to="images/events/"),
        ),
    ]
