# Generated by Django 4.1.7 on 2023-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_events_eimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="maddress",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
