# Generated by Django 4.1.7 on 2023-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_registration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="rwork",
            new_name="business_name",
        ),
        migrations.AddField(
            model_name="registration",
            name="remail",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
