# Generated by Django 4.1.7 on 2023-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_rwork_registration_business_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="rcontact",
        ),
        migrations.AddField(
            model_name="registration",
            name="rcontacts",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="members",
            name="mnumber",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="registration",
            name="raddress",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="registration",
            name="remail",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="rname",
            field=models.CharField(max_length=100),
        ),
    ]
