# Generated by Django 4.1.7 on 2023-04-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_registration_rcontact_registration_rcontacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacts",
            name="ccategory",
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
        migrations.DeleteModel(
            name="Contacts",
        ),
    ]
