# Generated by Django 4.1.7 on 2023-04-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_cityname_contactregistration_delete_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactregistration",
            name="rdocument",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
