# Generated by Django 4.1.7 on 2023-04-26 08:42

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_contactregistration_rdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactregistration",
            name="rdocument",
            field=models.FileField(
                null=True,
                upload_to="documents/",
                validators=[api.validators.validate_file_extension],
            ),
        ),
    ]
