# Generated by Django 4.1.7 on 2023-04-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_contactregistration_rdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_category", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="events",
            old_name="ename",
            new_name="eventname",
        ),
        migrations.AddField(
            model_name="events",
            name="booking_link",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="direction",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="event_contact",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="event_organiser",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="category_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventCategories",
                to="api.eventcategory",
            ),
        ),
    ]
