# Generated by Django 4.1.7 on 2023-04-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_eventcategory_rename_ename_events_eventname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_contact",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=20)),
                ("event_organiser", models.CharField(max_length=100, null=True)),
                ("event_contact", models.CharField(max_length=10, null=True)),
                ("event_address", models.CharField(max_length=50)),
                ("edate", models.DateField()),
                ("event_time", models.TimeField()),
                ("event_desc", models.CharField(max_length=200)),
                (
                    "event_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/eventsRegistration/"
                    ),
                ),
                ("booking_link", models.CharField(max_length=200, null=True)),
                ("direction", models.CharField(max_length=500, null=True)),
                (
                    "category_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventCategories_type",
                        to="api.eventcategory",
                    ),
                ),
            ],
        ),
    ]
