# Generated by Django 4.1.7 on 2023-04-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_event_organiser_events_eventorganiser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="eventOrganiser",
            new_name="organiser",
        ),
    ]
