# Generated by Django 4.1.7 on 2023-04-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_rename_eventorganiser_events_organiser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="organiser",
            new_name="organiser_name",
        ),
    ]
