# Generated by Django 4.1.7 on 2023-04-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_organiser_events_organiser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="booking_link",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="events",
            name="category_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventCategories",
                to="api.eventcategory",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="direction",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="events",
            name="eimage",
            field=models.ImageField(upload_to="images/events/"),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_contact",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="events",
            name="organiser_name",
            field=models.CharField(max_length=100),
        ),
    ]
