# Generated by Django 4.1.7 on 2023-06-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_contactregistration_rimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_image',
        ),
    ]
