# Generated by Django 4.1.7 on 2023-06-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_eventregistration_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_organiser', models.CharField(max_length=255)),
                ('event_contact', models.CharField(max_length=255)),
                ('event_address', models.CharField(max_length=255)),
                ('edate', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_desc', models.TextField()),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('booking_link', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=500)),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evecat')),
            ],
        ),
    ]
