# Generated by Django 4.1.7 on 2023-06-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_evecat_eventform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventcategory'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
