# Generated by Django 4.1.7 on 2023-06-23 06:14

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_eventform_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('alternate_contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('document', models.FileField(upload_to='documents/', validators=[api.validators.validate_file_extension])),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldname')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cityname')),
            ],
        ),
    ]
