# Generated by Django 4.1.7 on 2023-06-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_contform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
